#index:
#    path: /
#    controller: App\Controller\DefaultController::index

auth_check:
    path: /auth/check
    methods: [POST]

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }